config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :tasks
  get 'pages/home'
  root 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :category
	validates :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @tasknow = @category.tasks.where(category_id: params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @category = Category.find(params[:task][:category_id])
    @task = @category.tasks.create(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'View', @category %> |
<%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>CHOOSE A CATEGORY TO START!</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td style = "text-transform: uppercase; "><%= category.name %></td>
        <td><%= link_to 'VIEW', category, {:style => 'color: purple'} %></td>
        <td><%= link_to 'EDIT', edit_category_path(category)%></td>
        <td><%= link_to 'DELETE',  category, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'NEW CATEGORY', new_category_path, {:style => 'color:#ffc107'}  %>
</div>

app/views/categories/new.html.erb
<div class="container">
<h1>New Category</h1>

<%= render 'form', category: @category %>
<br>
<%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

<table>
  <thead>
    <h3>
  <strong> <%= @category.name %></strong>
</h3>
  </thead>

  <tbody>
     <% @tasknow.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td><%= link_to 'VIEW', task, {:style => 'color: purple'} %></td>
        <td><%= link_to 'EDIT', edit_task_path(task)%></td>
        <td><%= link_to 'DELETE',  task, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit Category', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
</div>

app/views/layouts/_header.html.erb
<nav>  
    <div class="nav-wrapper yellow lighten-5">
        <a href="#" class="brand-logo left amber">☺</a>
      <ul  class="right hide-on-med-and-down" style = "background-color:#ffc107">
         <li><%= link_to 'VIEW TASKS', tasks_path %></li>
         <li><%= link_to 'VIEW CATEGORIES', categories_path %></li>
        </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
 <tbody>	
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

app/views/tasks/_form.html.erb
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>           
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js">
        
      </script> 

<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row"> 
  
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category" },class: "browser-default" %> 
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>



<% end %>

app/views/tasks/edit.html.erb
<div class="container">
<h1>Editing Task</h1>

<%= render 'form', task: @task %>
<br>
<%= link_to 'View', @task %> |
<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>ALL TASKS</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td><%= task.category.name %> </td>
        <td><%= link_to 'VIEW', task, {:style => 'color: purple'} %></td>
        <td><%= link_to 'EDIT', edit_task_path(task)%></td>
        <td><%= link_to 'DELETE',  task, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'NEW TASK', new_task_path, {:style => 'color:#ffc107'}  %>
</div>

app/views/tasks/new.html.erb
<div class="container">
<h1>New Task</h1>

<%= render 'form', task: @task %>
<br>
<%= link_to 'Back', tasks_path %>

</div>

app/views/tasks/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>
</div>